name: continuous-integration

on:
  push:
    branches:
      - master
  pull_request:
    branches: ["master"]

jobs:
  lint-check:
    name: golangci-lint-v2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          args: --timeout 5m --config .golangci.yml
          version: v2.7.2 

  test-coverage:
    name: codecov-report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install Task CLI
        uses: arduino/setup-task@v2

      - name: Install Dependencies
        run: task deps

      - name: Tidy Modules
        run: task tidy

      - name: Run Coverage Tests
        run: task codecov

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
